import { Header } from '@/components/header'
import { Open_Sans } from 'next/font/google'
import './globals.css'
import Footer from '@/components/footer/index'

const inter = Open_Sans({ subsets: ['latin'] })

interface Metadata {
  title: string
  description: string
}

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt-br">
      <body className={inter.className}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  )
}
