import './globals.css'
import { Header } from '@/components/header'
import { Footer } from '@/components/footer'

interface Metadata {
  title: string
  description: string
}

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt-br">
      <body>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  )
}
